#161677517 Refactor user admin seed data to add isConfirmed user column and set default value
andela/haven-ah-backend pull request #23
Opened 2018-11-02 12:42 UTC by ucheg6

[Finishes #161677517]
#### What does this PR do?
- Refactor user admin seed data to add isConfirmed user column and set default value
#### Description of Task to be completed?
- Add the user column isConfirmed to the user admin seed data and set the default value to true

#### How should this be manually tested?
- git clone ` https://github.com/andela/haven-ah-backend.git `
- run npm install to install necessary npm packages
- create dot-env file and setup necessary variables for database configuration
-  run ` createdb haven-ah `to create the database
- run ` sequelize:migrate ` to migrate model
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#161677517](https://www.pivotaltracker.com/story/show/161677517)
#### Screenshots (if appropriate)
N/A
#### Questions:
N/A

2018-11-02 13:42 UTC, ProfJigsaw commented on server/seeders/20181026125921-user-admin.js
> +      isConfirmed: 'false',
admin should be confirmed by default

2018-11-02 14:01 UTC, ucheg6 commented on server/seeders/20181026125921-user-admin.js
> +      isConfirmed: 'false',
Thanks Victor. I just changed it

2018-11-05 09:08 UTC, seyi-adeleke requested changes
You didn't install or remove any packages so why is there a diff in your package.lock?

2018-11-05 09:28 UTC, ucheg6 commented
@seyi-adeleke I guess is when I tried to resolve a merge conflict

2018-11-05 15:25 UTC, seyi-adeleke reviewed
@ucheg6 Please ensure this works correctly on prod. You should probably sync with @ProfJigsaw

2018-11-05 15:25 UTC, seyi-adeleke approved these changes

2018-11-05 15:26 UTC, merged