#161924003 Add endpoint to update a user's role
andela/haven-ah-backend pull request #43
Opened 2018-11-14 14:27 UTC by PriscillaSam

#### What does this PR do?
Create endpoint to update a user's role. **PUT** `/api/v1/admin/users/roles`.

#### Description of Task to be completed
- add controller function for the endpoint
- test function and route with mocha and chai
- add documentation for the endpoint

#### How should this be manually tested?
- on the terminal run `git clone https://github.com/andela/haven-ah-backend.git`.
- run `git checkout ft-update-user-role-161924003`.
- ensure that PostgreSQL is running on your local machine.
- set up databases (test and development) following the `.env.sample` file.
- run `npm install` to install the npm packages.
- run `npm test` to run the unit and integration tests.
To test on postman

- run `npm run start-dev` and open up postman.

Authentication is required to perform this operation and is only available to the `SuperAdmin` role.

#### Screenshots where applicable

_Response when wrong enum type is passed_

<img width="1097" alt="screen shot 2018-11-14 at 2 05 47 pm" src="https://user-images.githubusercontent.com/29674347/48487909-d03ba480-e81f-11e8-895e-43eb8096e4cc.png">

_Response when user with username supplied does not exist._

<img width="1095" alt="screen shot 2018-11-14 at 2 06 35 pm" src="https://user-images.githubusercontent.com/29674347/48487936-de89c080-e81f-11e8-84d2-2aab6bdd355c.png">

 _Response when the operation is successful_

<img width="1105" alt="screen shot 2018-11-14 at 2 09 31 pm" src="https://user-images.githubusercontent.com/29674347/48487938-df225700-e81f-11e8-8b2d-5a96aca50b56.png">

#### Any background context to provide
The create user function was modified to include a role parameter.

#### What are the relevant pivotal tracker stories?
 #161924003

2018-11-15 08:39 UTC, ProfJigsaw commented
Looks good

2018-11-15 14:31 UTC, seyi-adeleke requested changes
there's a diff in your package lock

2018-11-16 12:14 UTC, TheoOkafor reviewed
It looks good. 👍

2018-11-16 12:14 UTC, TheoOkafor commented on server/controllers/user.js
> +    return goodHttpResponse(
Good stuff. @PriscillaSam 
Nice work

2018-11-16 15:24 UTC, seyi-adeleke approved these changes

2018-11-16 15:25 UTC, merged